name: Main workflow
on: [push]
env:
  container_name: internal-api
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21.5"
      - name: "Install depandencies from apt"
        run: |
          sudo apt update
          sudo apt install -y protobuf-compiler
      - name: "Install dependencies"
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
          export PATH="$PATH:$(go env GOPATH)/bin"
      - name: "Testing"
        run: |
          make test

  push:
    needs: [test]
    runs-on: ubuntu-latest
    if: "github.ref == 'refs/heads/main'"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 10
      - run: |
          set -x

          echo "${{ secrets.INTERNAL_API_ENV_FILE }}" > .env

          docker build . -t $container_name

          docker login --username ${{ secrets.DOCKER_USER }} --password ${{ secrets.DOCKER_USER_PASS }} ${{ vars.DOCKER_SERVER }}
          docker image tag $container_name ${{ vars.DOCKER_SERVER }}/$container_name
          docker push ${{ vars.DOCKER_SERVER }}/$container_name
